setwd("/Users/timdavies/Documents/Business/Projects/Young Lives/Phase 2/code/tools/spss_ddi_rdf/scripts")# install.packages("spssDDI");
data<-readSpssSav("../spss/etchildlevel12yrold.sav");
sink("../ddi/etchildlevel12yrold.xml");
writeDDI(data,"../ddi/etchildlevel12yrold.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/etchildlevel1yrold.sav");
sink("../ddi/etchildlevel1yrold.xml");
writeDDI(data,"../ddi/etchildlevel1yrold.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/etchildlevel5yrold.sav");
sink("../ddi/etchildlevel5yrold.xml");
writeDDI(data,"../ddi/etchildlevel5yrold.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/etchildlevel8yrold.sav");
sink("../ddi/etchildlevel8yrold.xml");
writeDDI(data,"../ddi/etchildlevel8yrold.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/etchildquest12yrold.sav");
sink("../ddi/etchildquest12yrold.xml");
writeDDI(data,"../ddi/etchildquest12yrold.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/etsubactivities12.sav");
sink("../ddi/etsubactivities12.xml");
writeDDI(data,"../ddi/etsubactivities12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/etsubactivities5.sav");
sink("../ddi/etsubactivities5.xml");
writeDDI(data,"../ddi/etsubactivities5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/etsubchildwork12.sav");
sink("../ddi/etsubchildwork12.xml");
writeDDI(data,"../ddi/etsubchildwork12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/etsubcreche5.sav");
sink("../ddi/etsubcreche5.xml");
writeDDI(data,"../ddi/etsubcreche5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/etsubcrops12.sav");
sink("../ddi/etsubcrops12.xml");
writeDDI(data,"../ddi/etsubcrops12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/etsubcrops5.sav");
sink("../ddi/etsubcrops5.xml");
writeDDI(data,"../ddi/etsubcrops5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/etsubgroups12.sav");
sink("../ddi/etsubgroups12.xml");
writeDDI(data,"../ddi/etsubgroups12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/etsubgroups5.sav");
sink("../ddi/etsubgroups5.xml");
writeDDI(data,"../ddi/etsubgroups5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/etsubhouseholdmember12.sav");
sink("../ddi/etsubhouseholdmember12.xml");
writeDDI(data,"../ddi/etsubhouseholdmember12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/etsubhouseholdmember5.sav");
sink("../ddi/etsubhouseholdmember5.xml");
writeDDI(data,"../ddi/etsubhouseholdmember5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/etsubillnesses12.sav");
sink("../ddi/etsubillnesses12.xml");
writeDDI(data,"../ddi/etsubillnesses12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/etsubillnesses5.sav");
sink("../ddi/etsubillnesses5.xml");
writeDDI(data,"../ddi/etsubillnesses5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/etsubinjuries12.sav");
sink("../ddi/etsubinjuries12.xml");
writeDDI(data,"../ddi/etsubinjuries12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/etsubinjuries5.sav");
sink("../ddi/etsubinjuries5.xml");
writeDDI(data,"../ddi/etsubinjuries5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/etsubloans12.sav");
sink("../ddi/etsubloans12.xml");
writeDDI(data,"../ddi/etsubloans12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/etsubloans5.sav");
sink("../ddi/etsubloans5.xml");
writeDDI(data,"../ddi/etsubloans5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/etsublongtermhealth12.sav");
sink("../ddi/etsublongtermhealth12.xml");
writeDDI(data,"../ddi/etsublongtermhealth12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/etsublongtermhealth5.sav");
sink("../ddi/etsublongtermhealth5.xml");
writeDDI(data,"../ddi/etsublongtermhealth5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/etsuboutgoings12.sav");
sink("../ddi/etsuboutgoings12.xml");
writeDDI(data,"../ddi/etsuboutgoings12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/etsuboutgoings5.sav");
sink("../ddi/etsuboutgoings5.xml");
writeDDI(data,"../ddi/etsuboutgoings5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/etsubplotsofland12.sav");
sink("../ddi/etsubplotsofland12.xml");
writeDDI(data,"../ddi/etsubplotsofland12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/etsubplotsofland5.sav");
sink("../ddi/etsubplotsofland5.xml");
writeDDI(data,"../ddi/etsubplotsofland5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/etsubpositionsofauthority12.sav");
sink("../ddi/etsubpositionsofauthority12.xml");
writeDDI(data,"../ddi/etsubpositionsofauthority12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/etsubpositionsofauthority5.sav");
sink("../ddi/etsubpositionsofauthority5.xml");
writeDDI(data,"../ddi/etsubpositionsofauthority5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/etsubpreschool5.sav");
sink("../ddi/etsubpreschool5.xml");
writeDDI(data,"../ddi/etsubpreschool5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/etsubprimaryoccupationproductiveassets12.sav");
sink("../ddi/etsubprimaryoccupationproductiveassets12.xml");
writeDDI(data,"../ddi/etsubprimaryoccupationproductiveassets12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/etsubprimaryoccupationproductiveassets5.sav");
sink("../ddi/etsubprimaryoccupationproductiveassets5.xml");
writeDDI(data,"../ddi/etsubprimaryoccupationproductiveassets5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/etsubsec2householdroster1.sav");
sink("../ddi/etsubsec2householdroster1.xml");
writeDDI(data,"../ddi/etsubsec2householdroster1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/etsubsec2householdroster8.sav");
sink("../ddi/etsubsec2householdroster8.xml");
writeDDI(data,"../ddi/etsubsec2householdroster8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/etsubsec4childcarers1.sav");
sink("../ddi/etsubsec4childcarers1.xml");
writeDDI(data,"../ddi/etsubsec4childcarers1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/etsubsec7childlivelihoods8.sav");
sink("../ddi/etsubsec7childlivelihoods8.xml");
writeDDI(data,"../ddi/etsubsec7childlivelihoods8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/etsubsec7hhlivelihoods1.sav");
sink("../ddi/etsubsec7hhlivelihoods1.xml");
writeDDI(data,"../ddi/etsubsec7hhlivelihoods1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/etsubsec7hhlivelihoods8.sav");
sink("../ddi/etsubsec7hhlivelihoods8.xml");
writeDDI(data,"../ddi/etsubsec7hhlivelihoods8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/etsubsec7indivincome1.sav");
sink("../ddi/etsubsec7indivincome1.xml");
writeDDI(data,"../ddi/etsubsec7indivincome1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/etsubsec7indivincome8.sav");
sink("../ddi/etsubsec7indivincome8.xml");
writeDDI(data,"../ddi/etsubsec7indivincome8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/etsubsec7outgoings1.sav");
sink("../ddi/etsubsec7outgoings1.xml");
writeDDI(data,"../ddi/etsubsec7outgoings1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/etsubsec7outgoings8.sav");
sink("../ddi/etsubsec7outgoings8.xml");
writeDDI(data,"../ddi/etsubsec7outgoings8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/etsubsec7plans1.sav");
sink("../ddi/etsubsec7plans1.xml");
writeDDI(data,"../ddi/etsubsec7plans1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/etsubsec7plans8.sav");
sink("../ddi/etsubsec7plans8.xml");
writeDDI(data,"../ddi/etsubsec7plans8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/etsubsec9plots1.sav");
sink("../ddi/etsubsec9plots1.xml");
writeDDI(data,"../ddi/etsubsec9plots1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/etsubsec9plots8.sav");
sink("../ddi/etsubsec9plots8.xml");
writeDDI(data,"../ddi/etsubsec9plots8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/etsubsecondaryoccupationproductiveassets12.sav");
sink("../ddi/etsubsecondaryoccupationproductiveassets12.xml");
writeDDI(data,"../ddi/etsubsecondaryoccupationproductiveassets12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/etsubsecondaryoccupationproductiveassets5.sav");
sink("../ddi/etsubsecondaryoccupationproductiveassets5.xml");
writeDDI(data,"../ddi/etsubsecondaryoccupationproductiveassets5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/etsubsupportprograms12.sav");
sink("../ddi/etsubsupportprograms12.xml");
writeDDI(data,"../ddi/etsubsupportprograms12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/etsubsupportprograms5.sav");
sink("../ddi/etsubsupportprograms5.xml");
writeDDI(data,"../ddi/etsubsupportprograms5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/inchildlevel12yrold.sav");
sink("../ddi/inchildlevel12yrold.xml");
writeDDI(data,"../ddi/inchildlevel12yrold.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/inchildlevel1yrold.sav");
sink("../ddi/inchildlevel1yrold.xml");
writeDDI(data,"../ddi/inchildlevel1yrold.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/inchildlevel5yrold.sav");
sink("../ddi/inchildlevel5yrold.xml");
writeDDI(data,"../ddi/inchildlevel5yrold.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/inchildlevel8yrold.sav");
sink("../ddi/inchildlevel8yrold.xml");
writeDDI(data,"../ddi/inchildlevel8yrold.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/inchildlevel8yrold_z.sav");
sink("../ddi/inchildlevel8yrold_z.xml");
writeDDI(data,"../ddi/inchildlevel8yrold_z.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/inchildquest12yrold.sav");
sink("../ddi/inchildquest12yrold.xml");
writeDDI(data,"../ddi/inchildquest12yrold.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/insubactivities5.sav");
sink("../ddi/insubactivities5.xml");
writeDDI(data,"../ddi/insubactivities5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/insubchildactivities12.sav");
sink("../ddi/insubchildactivities12.xml");
writeDDI(data,"../ddi/insubchildactivities12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/insubchildwork12.sav");
sink("../ddi/insubchildwork12.xml");
writeDDI(data,"../ddi/insubchildwork12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/insubchildwork5.sav");
sink("../ddi/insubchildwork5.xml");
writeDDI(data,"../ddi/insubchildwork5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/insubcreche5.sav");
sink("../ddi/insubcreche5.xml");
writeDDI(data,"../ddi/insubcreche5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/insubcrops12.sav");
sink("../ddi/insubcrops12.xml");
writeDDI(data,"../ddi/insubcrops12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/insubcrops5.sav");
sink("../ddi/insubcrops5.xml");
writeDDI(data,"../ddi/insubcrops5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/insubgroups12.sav");
sink("../ddi/insubgroups12.xml");
writeDDI(data,"../ddi/insubgroups12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/insubgroups5.sav");
sink("../ddi/insubgroups5.xml");
writeDDI(data,"../ddi/insubgroups5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/insubhouseholdmember12.sav");
sink("../ddi/insubhouseholdmember12.xml");
writeDDI(data,"../ddi/insubhouseholdmember12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/insubhouseholdmember5.sav");
sink("../ddi/insubhouseholdmember5.xml");
writeDDI(data,"../ddi/insubhouseholdmember5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/insubillnesses12.sav");
sink("../ddi/insubillnesses12.xml");
writeDDI(data,"../ddi/insubillnesses12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/insubillnesses5.sav");
sink("../ddi/insubillnesses5.xml");
writeDDI(data,"../ddi/insubillnesses5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/insubinjuries12.sav");
sink("../ddi/insubinjuries12.xml");
writeDDI(data,"../ddi/insubinjuries12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/insubinjuries5.sav");
sink("../ddi/insubinjuries5.xml");
writeDDI(data,"../ddi/insubinjuries5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/insublongtermhealth12.sav");
sink("../ddi/insublongtermhealth12.xml");
writeDDI(data,"../ddi/insublongtermhealth12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/insublongtermhealth5.sav");
sink("../ddi/insublongtermhealth5.xml");
writeDDI(data,"../ddi/insublongtermhealth5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/insuboutgoings12.sav");
sink("../ddi/insuboutgoings12.xml");
writeDDI(data,"../ddi/insuboutgoings12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/insuboutgoings5.sav");
sink("../ddi/insuboutgoings5.xml");
writeDDI(data,"../ddi/insuboutgoings5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/insubplotsofland12.sav");
sink("../ddi/insubplotsofland12.xml");
writeDDI(data,"../ddi/insubplotsofland12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/insubplotsofland5.sav");
sink("../ddi/insubplotsofland5.xml");
writeDDI(data,"../ddi/insubplotsofland5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/insubpositionsofauthority12.sav");
sink("../ddi/insubpositionsofauthority12.xml");
writeDDI(data,"../ddi/insubpositionsofauthority12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/insubpositionsofauthority5.sav");
sink("../ddi/insubpositionsofauthority5.xml");
writeDDI(data,"../ddi/insubpositionsofauthority5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/insubpreschool5.sav");
sink("../ddi/insubpreschool5.xml");
writeDDI(data,"../ddi/insubpreschool5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/insubprimaryoccupationproductiveassets12.sav");
sink("../ddi/insubprimaryoccupationproductiveassets12.xml");
writeDDI(data,"../ddi/insubprimaryoccupationproductiveassets12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/insubprimaryoccupationproductiveassets5.sav");
sink("../ddi/insubprimaryoccupationproductiveassets5.xml");
writeDDI(data,"../ddi/insubprimaryoccupationproductiveassets5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/insubsec2householdroster1.sav");
sink("../ddi/insubsec2householdroster1.xml");
writeDDI(data,"../ddi/insubsec2householdroster1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/insubsec2householdroster8.sav");
sink("../ddi/insubsec2householdroster8.xml");
writeDDI(data,"../ddi/insubsec2householdroster8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/insubsec4childcarers1.sav");
sink("../ddi/insubsec4childcarers1.xml");
writeDDI(data,"../ddi/insubsec4childcarers1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/insubsec7childlivelihoods8.sav");
sink("../ddi/insubsec7childlivelihoods8.xml");
writeDDI(data,"../ddi/insubsec7childlivelihoods8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/insubsec7hhlivelihoods1.sav");
sink("../ddi/insubsec7hhlivelihoods1.xml");
writeDDI(data,"../ddi/insubsec7hhlivelihoods1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/insubsec7hhlivelihoods8.sav");
sink("../ddi/insubsec7hhlivelihoods8.xml");
writeDDI(data,"../ddi/insubsec7hhlivelihoods8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/insubsec7indivincome1.sav");
sink("../ddi/insubsec7indivincome1.xml");
writeDDI(data,"../ddi/insubsec7indivincome1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/insubsec7indivincome8.sav");
sink("../ddi/insubsec7indivincome8.xml");
writeDDI(data,"../ddi/insubsec7indivincome8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/insubsec7outgoings1.sav");
sink("../ddi/insubsec7outgoings1.xml");
writeDDI(data,"../ddi/insubsec7outgoings1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/insubsec7outgoings8.sav");
sink("../ddi/insubsec7outgoings8.xml");
writeDDI(data,"../ddi/insubsec7outgoings8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/insubsec7plans1.sav");
sink("../ddi/insubsec7plans1.xml");
writeDDI(data,"../ddi/insubsec7plans1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/insubsec7plans8.sav");
sink("../ddi/insubsec7plans8.xml");
writeDDI(data,"../ddi/insubsec7plans8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/insubsec9plots1.sav");
sink("../ddi/insubsec9plots1.xml");
writeDDI(data,"../ddi/insubsec9plots1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/insubsec9plots8.sav");
sink("../ddi/insubsec9plots8.xml");
writeDDI(data,"../ddi/insubsec9plots8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/insubsecondaryoccupationproductiveassets12.sav");
sink("../ddi/insubsecondaryoccupationproductiveassets12.xml");
writeDDI(data,"../ddi/insubsecondaryoccupationproductiveassets12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/insubsecondaryoccupationproductiveassets5.sav");
sink("../ddi/insubsecondaryoccupationproductiveassets5.xml");
writeDDI(data,"../ddi/insubsecondaryoccupationproductiveassets5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pe1yroldurbanrural.sav");
sink("../ddi/pe1yroldurbanrural.xml");
writeDDI(data,"../ddi/pe1yroldurbanrural.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pe8yroldurbanrural.sav");
sink("../ddi/pe8yroldurbanrural.xml");
writeDDI(data,"../ddi/pe8yroldurbanrural.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pechildlevel12yrold.sav");
sink("../ddi/pechildlevel12yrold.xml");
writeDDI(data,"../ddi/pechildlevel12yrold.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pechildlevel1yrold.sav");
sink("../ddi/pechildlevel1yrold.xml");
writeDDI(data,"../ddi/pechildlevel1yrold.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pechildlevel5yrold.sav");
sink("../ddi/pechildlevel5yrold.xml");
writeDDI(data,"../ddi/pechildlevel5yrold.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pechildlevel8yrold.sav");
sink("../ddi/pechildlevel8yrold.xml");
writeDDI(data,"../ddi/pechildlevel8yrold.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pechildlevel8yrold_z.sav");
sink("../ddi/pechildlevel8yrold_z.xml");
writeDDI(data,"../ddi/pechildlevel8yrold_z.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pechildquest12yrold.sav");
sink("../ddi/pechildquest12yrold.xml");
writeDDI(data,"../ddi/pechildquest12yrold.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pesubactivities5.sav");
sink("../ddi/pesubactivities5.xml");
writeDDI(data,"../ddi/pesubactivities5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pesubchildactivities12.sav");
sink("../ddi/pesubchildactivities12.xml");
writeDDI(data,"../ddi/pesubchildactivities12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pesubchildwork12.sav");
sink("../ddi/pesubchildwork12.xml");
writeDDI(data,"../ddi/pesubchildwork12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pesubchildwork5.sav");
sink("../ddi/pesubchildwork5.xml");
writeDDI(data,"../ddi/pesubchildwork5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pesubcreche5.sav");
sink("../ddi/pesubcreche5.xml");
writeDDI(data,"../ddi/pesubcreche5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pesubcrops12.sav");
sink("../ddi/pesubcrops12.xml");
writeDDI(data,"../ddi/pesubcrops12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pesubcrops5.sav");
sink("../ddi/pesubcrops5.xml");
writeDDI(data,"../ddi/pesubcrops5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pesubdonatedfood12.sav");
sink("../ddi/pesubdonatedfood12.xml");
writeDDI(data,"../ddi/pesubdonatedfood12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pesubdonatedfood5.sav");
sink("../ddi/pesubdonatedfood5.xml");
writeDDI(data,"../ddi/pesubdonatedfood5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pesubfoodorganisations12.sav");
sink("../ddi/pesubfoodorganisations12.xml");
writeDDI(data,"../ddi/pesubfoodorganisations12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pesubfoodorganisations5.sav");
sink("../ddi/pesubfoodorganisations5.xml");
writeDDI(data,"../ddi/pesubfoodorganisations5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pesubgroups12.sav");
sink("../ddi/pesubgroups12.xml");
writeDDI(data,"../ddi/pesubgroups12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pesubgroups5.sav");
sink("../ddi/pesubgroups5.xml");
writeDDI(data,"../ddi/pesubgroups5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pesubhouseholdmember12.sav");
sink("../ddi/pesubhouseholdmember12.xml");
writeDDI(data,"../ddi/pesubhouseholdmember12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pesubhouseholdmember5.sav");
sink("../ddi/pesubhouseholdmember5.xml");
writeDDI(data,"../ddi/pesubhouseholdmember5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pesubillnesses12.sav");
sink("../ddi/pesubillnesses12.xml");
writeDDI(data,"../ddi/pesubillnesses12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pesubillnesses5.sav");
sink("../ddi/pesubillnesses5.xml");
writeDDI(data,"../ddi/pesubillnesses5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pesubinjuries12.sav");
sink("../ddi/pesubinjuries12.xml");
writeDDI(data,"../ddi/pesubinjuries12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pesubinjuries5.sav");
sink("../ddi/pesubinjuries5.xml");
writeDDI(data,"../ddi/pesubinjuries5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pesublongtermhealth12.sav");
sink("../ddi/pesublongtermhealth12.xml");
writeDDI(data,"../ddi/pesublongtermhealth12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pesublongtermhealth5.sav");
sink("../ddi/pesublongtermhealth5.xml");
writeDDI(data,"../ddi/pesublongtermhealth5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pesuboutgoings12.sav");
sink("../ddi/pesuboutgoings12.xml");
writeDDI(data,"../ddi/pesuboutgoings12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pesuboutgoings5.sav");
sink("../ddi/pesuboutgoings5.xml");
writeDDI(data,"../ddi/pesuboutgoings5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pesubplotsofland12.sav");
sink("../ddi/pesubplotsofland12.xml");
writeDDI(data,"../ddi/pesubplotsofland12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pesubplotsofland5.sav");
sink("../ddi/pesubplotsofland5.xml");
writeDDI(data,"../ddi/pesubplotsofland5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pesubpositionsofauthority12.sav");
sink("../ddi/pesubpositionsofauthority12.xml");
writeDDI(data,"../ddi/pesubpositionsofauthority12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pesubpositionsofauthority5.sav");
sink("../ddi/pesubpositionsofauthority5.xml");
writeDDI(data,"../ddi/pesubpositionsofauthority5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pesubpreschool5.sav");
sink("../ddi/pesubpreschool5.xml");
writeDDI(data,"../ddi/pesubpreschool5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pesubprimaryassets12.sav");
sink("../ddi/pesubprimaryassets12.xml");
writeDDI(data,"../ddi/pesubprimaryassets12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pesubprimaryassets5.sav");
sink("../ddi/pesubprimaryassets5.xml");
writeDDI(data,"../ddi/pesubprimaryassets5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pesubresidencychanges112.sav");
sink("../ddi/pesubresidencychanges112.xml");
writeDDI(data,"../ddi/pesubresidencychanges112.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pesubresidencychanges15.sav");
sink("../ddi/pesubresidencychanges15.xml");
writeDDI(data,"../ddi/pesubresidencychanges15.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pesubresidencychanges212.sav");
sink("../ddi/pesubresidencychanges212.xml");
writeDDI(data,"../ddi/pesubresidencychanges212.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pesubresidencychanges25.sav");
sink("../ddi/pesubresidencychanges25.xml");
writeDDI(data,"../ddi/pesubresidencychanges25.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pesubsec2householdroster1.sav");
sink("../ddi/pesubsec2householdroster1.xml");
writeDDI(data,"../ddi/pesubsec2householdroster1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pesubsec2householdroster8.sav");
sink("../ddi/pesubsec2householdroster8.xml");
writeDDI(data,"../ddi/pesubsec2householdroster8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pesubsec4childcarers1.sav");
sink("../ddi/pesubsec4childcarers1.xml");
writeDDI(data,"../ddi/pesubsec4childcarers1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pesubsec7chldlivelihoods8.sav");
sink("../ddi/pesubsec7chldlivelihoods8.xml");
writeDDI(data,"../ddi/pesubsec7chldlivelihoods8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pesubsec7hhlivelihoods1.sav");
sink("../ddi/pesubsec7hhlivelihoods1.xml");
writeDDI(data,"../ddi/pesubsec7hhlivelihoods1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pesubsec7hhlivelihoods8.sav");
sink("../ddi/pesubsec7hhlivelihoods8.xml");
writeDDI(data,"../ddi/pesubsec7hhlivelihoods8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pesubsec7indivincome1.sav");
sink("../ddi/pesubsec7indivincome1.xml");
writeDDI(data,"../ddi/pesubsec7indivincome1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pesubsec7indivincome8.sav");
sink("../ddi/pesubsec7indivincome8.xml");
writeDDI(data,"../ddi/pesubsec7indivincome8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pesubsec7outgoings1.sav");
sink("../ddi/pesubsec7outgoings1.xml");
writeDDI(data,"../ddi/pesubsec7outgoings1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pesubsec7outgoings8.sav");
sink("../ddi/pesubsec7outgoings8.xml");
writeDDI(data,"../ddi/pesubsec7outgoings8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pesubsec7plans1.sav");
sink("../ddi/pesubsec7plans1.xml");
writeDDI(data,"../ddi/pesubsec7plans1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pesubsec7plans8.sav");
sink("../ddi/pesubsec7plans8.xml");
writeDDI(data,"../ddi/pesubsec7plans8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pesubsec9plots1.sav");
sink("../ddi/pesubsec9plots1.xml");
writeDDI(data,"../ddi/pesubsec9plots1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/pesubsec9plots8.sav");
sink("../ddi/pesubsec9plots8.xml");
writeDDI(data,"../ddi/pesubsec9plots8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/vnchildlevel12yrold.sav");
sink("../ddi/vnchildlevel12yrold.xml");
writeDDI(data,"../ddi/vnchildlevel12yrold.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/vnchildlevel1yrold.sav");
sink("../ddi/vnchildlevel1yrold.xml");
writeDDI(data,"../ddi/vnchildlevel1yrold.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/vnchildlevel5yrold.sav");
sink("../ddi/vnchildlevel5yrold.xml");
writeDDI(data,"../ddi/vnchildlevel5yrold.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/vnchildlevel8yrold.sav");
sink("../ddi/vnchildlevel8yrold.xml");
writeDDI(data,"../ddi/vnchildlevel8yrold.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/vnchildquest12yrold.sav");
sink("../ddi/vnchildquest12yrold.xml");
writeDDI(data,"../ddi/vnchildquest12yrold.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/vnsubactivities12.sav");
sink("../ddi/vnsubactivities12.xml");
writeDDI(data,"../ddi/vnsubactivities12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/vnsubactivities5.sav");
sink("../ddi/vnsubactivities5.xml");
writeDDI(data,"../ddi/vnsubactivities5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/vnsubchildwork12.sav");
sink("../ddi/vnsubchildwork12.xml");
writeDDI(data,"../ddi/vnsubchildwork12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/vnsubchildwork5.sav");
sink("../ddi/vnsubchildwork5.xml");
writeDDI(data,"../ddi/vnsubchildwork5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/vnsubcreche5.sav");
sink("../ddi/vnsubcreche5.xml");
writeDDI(data,"../ddi/vnsubcreche5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/vnsubcrops12.sav");
sink("../ddi/vnsubcrops12.xml");
writeDDI(data,"../ddi/vnsubcrops12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/vnsubcrops5.sav");
sink("../ddi/vnsubcrops5.xml");
writeDDI(data,"../ddi/vnsubcrops5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/vnsubgroups12.sav");
sink("../ddi/vnsubgroups12.xml");
writeDDI(data,"../ddi/vnsubgroups12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/vnsubgroups5.sav");
sink("../ddi/vnsubgroups5.xml");
writeDDI(data,"../ddi/vnsubgroups5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/vnsubhouseholdmember12.sav");
sink("../ddi/vnsubhouseholdmember12.xml");
writeDDI(data,"../ddi/vnsubhouseholdmember12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/vnsubhouseholdmember5.sav");
sink("../ddi/vnsubhouseholdmember5.xml");
writeDDI(data,"../ddi/vnsubhouseholdmember5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/vnsubillnesses12.sav");
sink("../ddi/vnsubillnesses12.xml");
writeDDI(data,"../ddi/vnsubillnesses12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/vnsubillnesses5.sav");
sink("../ddi/vnsubillnesses5.xml");
writeDDI(data,"../ddi/vnsubillnesses5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/vnsubinjuries12.sav");
sink("../ddi/vnsubinjuries12.xml");
writeDDI(data,"../ddi/vnsubinjuries12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/vnsubinjuries5.sav");
sink("../ddi/vnsubinjuries5.xml");
writeDDI(data,"../ddi/vnsubinjuries5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/vnsubloans12.sav");
sink("../ddi/vnsubloans12.xml");
writeDDI(data,"../ddi/vnsubloans12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/vnsubloans5.sav");
sink("../ddi/vnsubloans5.xml");
writeDDI(data,"../ddi/vnsubloans5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/vnsublongtermhealth12.sav");
sink("../ddi/vnsublongtermhealth12.xml");
writeDDI(data,"../ddi/vnsublongtermhealth12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/vnsublongtermhealth5.sav");
sink("../ddi/vnsublongtermhealth5.xml");
writeDDI(data,"../ddi/vnsublongtermhealth5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/vnsuboutgoings12.sav");
sink("../ddi/vnsuboutgoings12.xml");
writeDDI(data,"../ddi/vnsuboutgoings12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/vnsuboutgoings5.sav");
sink("../ddi/vnsuboutgoings5.xml");
writeDDI(data,"../ddi/vnsuboutgoings5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/vnsubplotsofland12.sav");
sink("../ddi/vnsubplotsofland12.xml");
writeDDI(data,"../ddi/vnsubplotsofland12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/vnsubplotsofland5.sav");
sink("../ddi/vnsubplotsofland5.xml");
writeDDI(data,"../ddi/vnsubplotsofland5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/vnsubpositionsofauthority12.sav");
sink("../ddi/vnsubpositionsofauthority12.xml");
writeDDI(data,"../ddi/vnsubpositionsofauthority12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/vnsubpositionsofauthority5.sav");
sink("../ddi/vnsubpositionsofauthority5.xml");
writeDDI(data,"../ddi/vnsubpositionsofauthority5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/vnsubpreschool5.sav");
sink("../ddi/vnsubpreschool5.xml");
writeDDI(data,"../ddi/vnsubpreschool5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/vnsubprimaryoccupationproductiveassets12.sav");
sink("../ddi/vnsubprimaryoccupationproductiveassets12.xml");
writeDDI(data,"../ddi/vnsubprimaryoccupationproductiveassets12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/vnsubprimaryoccupationproductiveassets5.sav");
sink("../ddi/vnsubprimaryoccupationproductiveassets5.xml");
writeDDI(data,"../ddi/vnsubprimaryoccupationproductiveassets5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/vnsubprojects12.sav");
sink("../ddi/vnsubprojects12.xml");
writeDDI(data,"../ddi/vnsubprojects12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/vnsubprojects5.sav");
sink("../ddi/vnsubprojects5.xml");
writeDDI(data,"../ddi/vnsubprojects5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/vnsubsec2householdroster1.sav");
sink("../ddi/vnsubsec2householdroster1.xml");
writeDDI(data,"../ddi/vnsubsec2householdroster1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/vnsubsec2householdroster8.sav");
sink("../ddi/vnsubsec2householdroster8.xml");
writeDDI(data,"../ddi/vnsubsec2householdroster8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/vnsubsec4childcarers1.sav");
sink("../ddi/vnsubsec4childcarers1.xml");
writeDDI(data,"../ddi/vnsubsec4childcarers1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/vnsubsec7chldlivelihoods8.sav");
sink("../ddi/vnsubsec7chldlivelihoods8.xml");
writeDDI(data,"../ddi/vnsubsec7chldlivelihoods8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/vnsubsec7hhlivelihoods1.sav");
sink("../ddi/vnsubsec7hhlivelihoods1.xml");
writeDDI(data,"../ddi/vnsubsec7hhlivelihoods1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/vnsubsec7hhlivelihoods8.sav");
sink("../ddi/vnsubsec7hhlivelihoods8.xml");
writeDDI(data,"../ddi/vnsubsec7hhlivelihoods8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/vnsubsec7indivincome1.sav");
sink("../ddi/vnsubsec7indivincome1.xml");
writeDDI(data,"../ddi/vnsubsec7indivincome1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/vnsubsec7indivincome8.sav");
sink("../ddi/vnsubsec7indivincome8.xml");
writeDDI(data,"../ddi/vnsubsec7indivincome8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/vnsubsec7outgoings1.sav");
sink("../ddi/vnsubsec7outgoings1.xml");
writeDDI(data,"../ddi/vnsubsec7outgoings1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/vnsubsec7outgoings8.sav");
sink("../ddi/vnsubsec7outgoings8.xml");
writeDDI(data,"../ddi/vnsubsec7outgoings8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/vnsubsec7plans1.sav");
sink("../ddi/vnsubsec7plans1.xml");
writeDDI(data,"../ddi/vnsubsec7plans1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/vnsubsec7plans8.sav");
sink("../ddi/vnsubsec7plans8.xml");
writeDDI(data,"../ddi/vnsubsec7plans8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/vnsubsec9plots1.sav");
sink("../ddi/vnsubsec9plots1.xml");
writeDDI(data,"../ddi/vnsubsec9plots1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/vnsubsec9plots8.sav");
sink("../ddi/vnsubsec9plots8.xml");
writeDDI(data,"../ddi/vnsubsec9plots8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/vnsubsecondaryoccupationproductiveassets12.sav");
sink("../ddi/vnsubsecondaryoccupationproductiveassets12.xml");
writeDDI(data,"../ddi/vnsubsecondaryoccupationproductiveassets12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../spss/vnsubsecondaryoccupationproductiveassets5.sav");
sink("../ddi/vnsubsecondaryoccupationproductiveassets5.xml");
writeDDI(data,"../ddi/vnsubsecondaryoccupationproductiveassets5.xml");
sink();