library("spssDDI");
setwd("/Users/timdavies/Documents/Business/Projects/Young Lives/Phase 2/code/IKMLinkedResearch/tools/spss_ddi_rdf/scripts")# install.packages("spssDDI");
data<-readSpssSav("../data/spss/etchildlevel12yrold.sav");
sink("../data/ddi/etchildlevel12yrold.xml");
writeDDI(data,"../data/ddi/etchildlevel12yrold.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/etchildlevel1yrold.sav");
sink("../data/ddi/etchildlevel1yrold.xml");
writeDDI(data,"../data/ddi/etchildlevel1yrold.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/etchildlevel5yrold.sav");
sink("../data/ddi/etchildlevel5yrold.xml");
writeDDI(data,"../data/ddi/etchildlevel5yrold.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/etchildlevel8yrold.sav");
sink("../data/ddi/etchildlevel8yrold.xml");
writeDDI(data,"../data/ddi/etchildlevel8yrold.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/etchildquest12yrold.sav");
sink("../data/ddi/etchildquest12yrold.xml");
writeDDI(data,"../data/ddi/etchildquest12yrold.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/etsubactivities12.sav");
sink("../data/ddi/etsubactivities12.xml");
writeDDI(data,"../data/ddi/etsubactivities12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/etsubactivities5.sav");
sink("../data/ddi/etsubactivities5.xml");
writeDDI(data,"../data/ddi/etsubactivities5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/etsubchildwork12.sav");
sink("../data/ddi/etsubchildwork12.xml");
writeDDI(data,"../data/ddi/etsubchildwork12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/etsubcreche5.sav");
sink("../data/ddi/etsubcreche5.xml");
writeDDI(data,"../data/ddi/etsubcreche5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/etsubcrops12.sav");
sink("../data/ddi/etsubcrops12.xml");
writeDDI(data,"../data/ddi/etsubcrops12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/etsubcrops5.sav");
sink("../data/ddi/etsubcrops5.xml");
writeDDI(data,"../data/ddi/etsubcrops5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/etsubgroups12.sav");
sink("../data/ddi/etsubgroups12.xml");
writeDDI(data,"../data/ddi/etsubgroups12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/etsubgroups5.sav");
sink("../data/ddi/etsubgroups5.xml");
writeDDI(data,"../data/ddi/etsubgroups5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/etsubhouseholdmember12.sav");
sink("../data/ddi/etsubhouseholdmember12.xml");
writeDDI(data,"../data/ddi/etsubhouseholdmember12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/etsubhouseholdmember5.sav");
sink("../data/ddi/etsubhouseholdmember5.xml");
writeDDI(data,"../data/ddi/etsubhouseholdmember5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/etsubillnesses12.sav");
sink("../data/ddi/etsubillnesses12.xml");
writeDDI(data,"../data/ddi/etsubillnesses12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/etsubillnesses5.sav");
sink("../data/ddi/etsubillnesses5.xml");
writeDDI(data,"../data/ddi/etsubillnesses5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/etsubinjuries12.sav");
sink("../data/ddi/etsubinjuries12.xml");
writeDDI(data,"../data/ddi/etsubinjuries12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/etsubinjuries5.sav");
sink("../data/ddi/etsubinjuries5.xml");
writeDDI(data,"../data/ddi/etsubinjuries5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/etsubloans12.sav");
sink("../data/ddi/etsubloans12.xml");
writeDDI(data,"../data/ddi/etsubloans12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/etsubloans5.sav");
sink("../data/ddi/etsubloans5.xml");
writeDDI(data,"../data/ddi/etsubloans5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/etsublongtermhealth12.sav");
sink("../data/ddi/etsublongtermhealth12.xml");
writeDDI(data,"../data/ddi/etsublongtermhealth12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/etsublongtermhealth5.sav");
sink("../data/ddi/etsublongtermhealth5.xml");
writeDDI(data,"../data/ddi/etsublongtermhealth5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/etsuboutgoings12.sav");
sink("../data/ddi/etsuboutgoings12.xml");
writeDDI(data,"../data/ddi/etsuboutgoings12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/etsuboutgoings5.sav");
sink("../data/ddi/etsuboutgoings5.xml");
writeDDI(data,"../data/ddi/etsuboutgoings5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/etsubplotsofland12.sav");
sink("../data/ddi/etsubplotsofland12.xml");
writeDDI(data,"../data/ddi/etsubplotsofland12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/etsubplotsofland5.sav");
sink("../data/ddi/etsubplotsofland5.xml");
writeDDI(data,"../data/ddi/etsubplotsofland5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/etsubpositionsofauthority12.sav");
sink("../data/ddi/etsubpositionsofauthority12.xml");
writeDDI(data,"../data/ddi/etsubpositionsofauthority12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/etsubpositionsofauthority5.sav");
sink("../data/ddi/etsubpositionsofauthority5.xml");
writeDDI(data,"../data/ddi/etsubpositionsofauthority5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/etsubpreschool5.sav");
sink("../data/ddi/etsubpreschool5.xml");
writeDDI(data,"../data/ddi/etsubpreschool5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/etsubprimaryoccupationproductiveassets12.sav");
sink("../data/ddi/etsubprimaryoccupationproductiveassets12.xml");
writeDDI(data,"../data/ddi/etsubprimaryoccupationproductiveassets12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/etsubprimaryoccupationproductiveassets5.sav");
sink("../data/ddi/etsubprimaryoccupationproductiveassets5.xml");
writeDDI(data,"../data/ddi/etsubprimaryoccupationproductiveassets5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/etsubsec2householdroster1.sav");
sink("../data/ddi/etsubsec2householdroster1.xml");
writeDDI(data,"../data/ddi/etsubsec2householdroster1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/etsubsec2householdroster8.sav");
sink("../data/ddi/etsubsec2householdroster8.xml");
writeDDI(data,"../data/ddi/etsubsec2householdroster8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/etsubsec4childcarers1.sav");
sink("../data/ddi/etsubsec4childcarers1.xml");
writeDDI(data,"../data/ddi/etsubsec4childcarers1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/etsubsec7childlivelihoods8.sav");
sink("../data/ddi/etsubsec7childlivelihoods8.xml");
writeDDI(data,"../data/ddi/etsubsec7childlivelihoods8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/etsubsec7hhlivelihoods1.sav");
sink("../data/ddi/etsubsec7hhlivelihoods1.xml");
writeDDI(data,"../data/ddi/etsubsec7hhlivelihoods1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/etsubsec7hhlivelihoods8.sav");
sink("../data/ddi/etsubsec7hhlivelihoods8.xml");
writeDDI(data,"../data/ddi/etsubsec7hhlivelihoods8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/etsubsec7indivincome1.sav");
sink("../data/ddi/etsubsec7indivincome1.xml");
writeDDI(data,"../data/ddi/etsubsec7indivincome1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/etsubsec7indivincome8.sav");
sink("../data/ddi/etsubsec7indivincome8.xml");
writeDDI(data,"../data/ddi/etsubsec7indivincome8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/etsubsec7outgoings1.sav");
sink("../data/ddi/etsubsec7outgoings1.xml");
writeDDI(data,"../data/ddi/etsubsec7outgoings1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/etsubsec7outgoings8.sav");
sink("../data/ddi/etsubsec7outgoings8.xml");
writeDDI(data,"../data/ddi/etsubsec7outgoings8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/etsubsec7plans1.sav");
sink("../data/ddi/etsubsec7plans1.xml");
writeDDI(data,"../data/ddi/etsubsec7plans1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/etsubsec7plans8.sav");
sink("../data/ddi/etsubsec7plans8.xml");
writeDDI(data,"../data/ddi/etsubsec7plans8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/etsubsec9plots1.sav");
sink("../data/ddi/etsubsec9plots1.xml");
writeDDI(data,"../data/ddi/etsubsec9plots1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/etsubsec9plots8.sav");
sink("../data/ddi/etsubsec9plots8.xml");
writeDDI(data,"../data/ddi/etsubsec9plots8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/etsubsecondaryoccupationproductiveassets12.sav");
sink("../data/ddi/etsubsecondaryoccupationproductiveassets12.xml");
writeDDI(data,"../data/ddi/etsubsecondaryoccupationproductiveassets12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/etsubsecondaryoccupationproductiveassets5.sav");
sink("../data/ddi/etsubsecondaryoccupationproductiveassets5.xml");
writeDDI(data,"../data/ddi/etsubsecondaryoccupationproductiveassets5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/etsubsupportprograms12.sav");
sink("../data/ddi/etsubsupportprograms12.xml");
writeDDI(data,"../data/ddi/etsubsupportprograms12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/etsubsupportprograms5.sav");
sink("../data/ddi/etsubsupportprograms5.xml");
writeDDI(data,"../data/ddi/etsubsupportprograms5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/inchildlevel12yrold.sav");
sink("../data/ddi/inchildlevel12yrold.xml");
writeDDI(data,"../data/ddi/inchildlevel12yrold.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/inchildlevel1yrold.sav");
sink("../data/ddi/inchildlevel1yrold.xml");
writeDDI(data,"../data/ddi/inchildlevel1yrold.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/inchildlevel5yrold.sav");
sink("../data/ddi/inchildlevel5yrold.xml");
writeDDI(data,"../data/ddi/inchildlevel5yrold.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/inchildlevel8yrold.sav");
sink("../data/ddi/inchildlevel8yrold.xml");
writeDDI(data,"../data/ddi/inchildlevel8yrold.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/inchildlevel8yrold_z.sav");
sink("../data/ddi/inchildlevel8yrold_z.xml");
writeDDI(data,"../data/ddi/inchildlevel8yrold_z.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/inchildquest12yrold.sav");
sink("../data/ddi/inchildquest12yrold.xml");
writeDDI(data,"../data/ddi/inchildquest12yrold.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/insubactivities5.sav");
sink("../data/ddi/insubactivities5.xml");
writeDDI(data,"../data/ddi/insubactivities5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/insubchildactivities12.sav");
sink("../data/ddi/insubchildactivities12.xml");
writeDDI(data,"../data/ddi/insubchildactivities12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/insubchildwork12.sav");
sink("../data/ddi/insubchildwork12.xml");
writeDDI(data,"../data/ddi/insubchildwork12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/insubchildwork5.sav");
sink("../data/ddi/insubchildwork5.xml");
writeDDI(data,"../data/ddi/insubchildwork5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/insubcreche5.sav");
sink("../data/ddi/insubcreche5.xml");
writeDDI(data,"../data/ddi/insubcreche5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/insubcrops12.sav");
sink("../data/ddi/insubcrops12.xml");
writeDDI(data,"../data/ddi/insubcrops12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/insubcrops5.sav");
sink("../data/ddi/insubcrops5.xml");
writeDDI(data,"../data/ddi/insubcrops5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/insubgroups12.sav");
sink("../data/ddi/insubgroups12.xml");
writeDDI(data,"../data/ddi/insubgroups12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/insubgroups5.sav");
sink("../data/ddi/insubgroups5.xml");
writeDDI(data,"../data/ddi/insubgroups5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/insubhouseholdmember12.sav");
sink("../data/ddi/insubhouseholdmember12.xml");
writeDDI(data,"../data/ddi/insubhouseholdmember12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/insubhouseholdmember5.sav");
sink("../data/ddi/insubhouseholdmember5.xml");
writeDDI(data,"../data/ddi/insubhouseholdmember5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/insubillnesses12.sav");
sink("../data/ddi/insubillnesses12.xml");
writeDDI(data,"../data/ddi/insubillnesses12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/insubillnesses5.sav");
sink("../data/ddi/insubillnesses5.xml");
writeDDI(data,"../data/ddi/insubillnesses5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/insubinjuries12.sav");
sink("../data/ddi/insubinjuries12.xml");
writeDDI(data,"../data/ddi/insubinjuries12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/insubinjuries5.sav");
sink("../data/ddi/insubinjuries5.xml");
writeDDI(data,"../data/ddi/insubinjuries5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/insublongtermhealth12.sav");
sink("../data/ddi/insublongtermhealth12.xml");
writeDDI(data,"../data/ddi/insublongtermhealth12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/insublongtermhealth5.sav");
sink("../data/ddi/insublongtermhealth5.xml");
writeDDI(data,"../data/ddi/insublongtermhealth5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/insuboutgoings12.sav");
sink("../data/ddi/insuboutgoings12.xml");
writeDDI(data,"../data/ddi/insuboutgoings12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/insuboutgoings5.sav");
sink("../data/ddi/insuboutgoings5.xml");
writeDDI(data,"../data/ddi/insuboutgoings5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/insubplotsofland12.sav");
sink("../data/ddi/insubplotsofland12.xml");
writeDDI(data,"../data/ddi/insubplotsofland12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/insubplotsofland5.sav");
sink("../data/ddi/insubplotsofland5.xml");
writeDDI(data,"../data/ddi/insubplotsofland5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/insubpositionsofauthority12.sav");
sink("../data/ddi/insubpositionsofauthority12.xml");
writeDDI(data,"../data/ddi/insubpositionsofauthority12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/insubpositionsofauthority5.sav");
sink("../data/ddi/insubpositionsofauthority5.xml");
writeDDI(data,"../data/ddi/insubpositionsofauthority5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/insubpreschool5.sav");
sink("../data/ddi/insubpreschool5.xml");
writeDDI(data,"../data/ddi/insubpreschool5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/insubprimaryoccupationproductiveassets12.sav");
sink("../data/ddi/insubprimaryoccupationproductiveassets12.xml");
writeDDI(data,"../data/ddi/insubprimaryoccupationproductiveassets12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/insubprimaryoccupationproductiveassets5.sav");
sink("../data/ddi/insubprimaryoccupationproductiveassets5.xml");
writeDDI(data,"../data/ddi/insubprimaryoccupationproductiveassets5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/insubsec2householdroster1.sav");
sink("../data/ddi/insubsec2householdroster1.xml");
writeDDI(data,"../data/ddi/insubsec2householdroster1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/insubsec2householdroster8.sav");
sink("../data/ddi/insubsec2householdroster8.xml");
writeDDI(data,"../data/ddi/insubsec2householdroster8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/insubsec4childcarers1.sav");
sink("../data/ddi/insubsec4childcarers1.xml");
writeDDI(data,"../data/ddi/insubsec4childcarers1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/insubsec7childlivelihoods8.sav");
sink("../data/ddi/insubsec7childlivelihoods8.xml");
writeDDI(data,"../data/ddi/insubsec7childlivelihoods8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/insubsec7hhlivelihoods1.sav");
sink("../data/ddi/insubsec7hhlivelihoods1.xml");
writeDDI(data,"../data/ddi/insubsec7hhlivelihoods1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/insubsec7hhlivelihoods8.sav");
sink("../data/ddi/insubsec7hhlivelihoods8.xml");
writeDDI(data,"../data/ddi/insubsec7hhlivelihoods8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/insubsec7indivincome1.sav");
sink("../data/ddi/insubsec7indivincome1.xml");
writeDDI(data,"../data/ddi/insubsec7indivincome1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/insubsec7indivincome8.sav");
sink("../data/ddi/insubsec7indivincome8.xml");
writeDDI(data,"../data/ddi/insubsec7indivincome8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/insubsec7outgoings1.sav");
sink("../data/ddi/insubsec7outgoings1.xml");
writeDDI(data,"../data/ddi/insubsec7outgoings1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/insubsec7outgoings8.sav");
sink("../data/ddi/insubsec7outgoings8.xml");
writeDDI(data,"../data/ddi/insubsec7outgoings8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/insubsec7plans1.sav");
sink("../data/ddi/insubsec7plans1.xml");
writeDDI(data,"../data/ddi/insubsec7plans1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/insubsec7plans8.sav");
sink("../data/ddi/insubsec7plans8.xml");
writeDDI(data,"../data/ddi/insubsec7plans8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/insubsec9plots1.sav");
sink("../data/ddi/insubsec9plots1.xml");
writeDDI(data,"../data/ddi/insubsec9plots1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/insubsec9plots8.sav");
sink("../data/ddi/insubsec9plots8.xml");
writeDDI(data,"../data/ddi/insubsec9plots8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/insubsecondaryoccupationproductiveassets12.sav");
sink("../data/ddi/insubsecondaryoccupationproductiveassets12.xml");
writeDDI(data,"../data/ddi/insubsecondaryoccupationproductiveassets12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/insubsecondaryoccupationproductiveassets5.sav");
sink("../data/ddi/insubsecondaryoccupationproductiveassets5.xml");
writeDDI(data,"../data/ddi/insubsecondaryoccupationproductiveassets5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pe1yroldurbanrural.sav");
sink("../data/ddi/pe1yroldurbanrural.xml");
writeDDI(data,"../data/ddi/pe1yroldurbanrural.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pe8yroldurbanrural.sav");
sink("../data/ddi/pe8yroldurbanrural.xml");
writeDDI(data,"../data/ddi/pe8yroldurbanrural.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pechildlevel12yrold.sav");
sink("../data/ddi/pechildlevel12yrold.xml");
writeDDI(data,"../data/ddi/pechildlevel12yrold.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pechildlevel1yrold.sav");
sink("../data/ddi/pechildlevel1yrold.xml");
writeDDI(data,"../data/ddi/pechildlevel1yrold.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pechildlevel5yrold.sav");
sink("../data/ddi/pechildlevel5yrold.xml");
writeDDI(data,"../data/ddi/pechildlevel5yrold.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pechildlevel8yrold.sav");
sink("../data/ddi/pechildlevel8yrold.xml");
writeDDI(data,"../data/ddi/pechildlevel8yrold.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pechildlevel8yrold_z.sav");
sink("../data/ddi/pechildlevel8yrold_z.xml");
writeDDI(data,"../data/ddi/pechildlevel8yrold_z.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pechildquest12yrold.sav");
sink("../data/ddi/pechildquest12yrold.xml");
writeDDI(data,"../data/ddi/pechildquest12yrold.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pesubactivities5.sav");
sink("../data/ddi/pesubactivities5.xml");
writeDDI(data,"../data/ddi/pesubactivities5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pesubchildactivities12.sav");
sink("../data/ddi/pesubchildactivities12.xml");
writeDDI(data,"../data/ddi/pesubchildactivities12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pesubchildwork12.sav");
sink("../data/ddi/pesubchildwork12.xml");
writeDDI(data,"../data/ddi/pesubchildwork12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pesubchildwork5.sav");
sink("../data/ddi/pesubchildwork5.xml");
writeDDI(data,"../data/ddi/pesubchildwork5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pesubcreche5.sav");
sink("../data/ddi/pesubcreche5.xml");
writeDDI(data,"../data/ddi/pesubcreche5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pesubcrops12.sav");
sink("../data/ddi/pesubcrops12.xml");
writeDDI(data,"../data/ddi/pesubcrops12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pesubcrops5.sav");
sink("../data/ddi/pesubcrops5.xml");
writeDDI(data,"../data/ddi/pesubcrops5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pesubdonatedfood12.sav");
sink("../data/ddi/pesubdonatedfood12.xml");
writeDDI(data,"../data/ddi/pesubdonatedfood12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pesubdonatedfood5.sav");
sink("../data/ddi/pesubdonatedfood5.xml");
writeDDI(data,"../data/ddi/pesubdonatedfood5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pesubfoodorganisations12.sav");
sink("../data/ddi/pesubfoodorganisations12.xml");
writeDDI(data,"../data/ddi/pesubfoodorganisations12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pesubfoodorganisations5.sav");
sink("../data/ddi/pesubfoodorganisations5.xml");
writeDDI(data,"../data/ddi/pesubfoodorganisations5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pesubgroups12.sav");
sink("../data/ddi/pesubgroups12.xml");
writeDDI(data,"../data/ddi/pesubgroups12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pesubgroups5.sav");
sink("../data/ddi/pesubgroups5.xml");
writeDDI(data,"../data/ddi/pesubgroups5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pesubhouseholdmember12.sav");
sink("../data/ddi/pesubhouseholdmember12.xml");
writeDDI(data,"../data/ddi/pesubhouseholdmember12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pesubhouseholdmember5.sav");
sink("../data/ddi/pesubhouseholdmember5.xml");
writeDDI(data,"../data/ddi/pesubhouseholdmember5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pesubillnesses12.sav");
sink("../data/ddi/pesubillnesses12.xml");
writeDDI(data,"../data/ddi/pesubillnesses12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pesubillnesses5.sav");
sink("../data/ddi/pesubillnesses5.xml");
writeDDI(data,"../data/ddi/pesubillnesses5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pesubinjuries12.sav");
sink("../data/ddi/pesubinjuries12.xml");
writeDDI(data,"../data/ddi/pesubinjuries12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pesubinjuries5.sav");
sink("../data/ddi/pesubinjuries5.xml");
writeDDI(data,"../data/ddi/pesubinjuries5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pesublongtermhealth12.sav");
sink("../data/ddi/pesublongtermhealth12.xml");
writeDDI(data,"../data/ddi/pesublongtermhealth12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pesublongtermhealth5.sav");
sink("../data/ddi/pesublongtermhealth5.xml");
writeDDI(data,"../data/ddi/pesublongtermhealth5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pesuboutgoings12.sav");
sink("../data/ddi/pesuboutgoings12.xml");
writeDDI(data,"../data/ddi/pesuboutgoings12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pesuboutgoings5.sav");
sink("../data/ddi/pesuboutgoings5.xml");
writeDDI(data,"../data/ddi/pesuboutgoings5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pesubplotsofland12.sav");
sink("../data/ddi/pesubplotsofland12.xml");
writeDDI(data,"../data/ddi/pesubplotsofland12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pesubplotsofland5.sav");
sink("../data/ddi/pesubplotsofland5.xml");
writeDDI(data,"../data/ddi/pesubplotsofland5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pesubpositionsofauthority12.sav");
sink("../data/ddi/pesubpositionsofauthority12.xml");
writeDDI(data,"../data/ddi/pesubpositionsofauthority12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pesubpositionsofauthority5.sav");
sink("../data/ddi/pesubpositionsofauthority5.xml");
writeDDI(data,"../data/ddi/pesubpositionsofauthority5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pesubpreschool5.sav");
sink("../data/ddi/pesubpreschool5.xml");
writeDDI(data,"../data/ddi/pesubpreschool5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pesubprimaryassets12.sav");
sink("../data/ddi/pesubprimaryassets12.xml");
writeDDI(data,"../data/ddi/pesubprimaryassets12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pesubprimaryassets5.sav");
sink("../data/ddi/pesubprimaryassets5.xml");
writeDDI(data,"../data/ddi/pesubprimaryassets5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pesubresidencychanges112.sav");
sink("../data/ddi/pesubresidencychanges112.xml");
writeDDI(data,"../data/ddi/pesubresidencychanges112.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pesubresidencychanges15.sav");
sink("../data/ddi/pesubresidencychanges15.xml");
writeDDI(data,"../data/ddi/pesubresidencychanges15.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pesubresidencychanges212.sav");
sink("../data/ddi/pesubresidencychanges212.xml");
writeDDI(data,"../data/ddi/pesubresidencychanges212.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pesubresidencychanges25.sav");
sink("../data/ddi/pesubresidencychanges25.xml");
writeDDI(data,"../data/ddi/pesubresidencychanges25.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pesubsec2householdroster1.sav");
sink("../data/ddi/pesubsec2householdroster1.xml");
writeDDI(data,"../data/ddi/pesubsec2householdroster1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pesubsec2householdroster8.sav");
sink("../data/ddi/pesubsec2householdroster8.xml");
writeDDI(data,"../data/ddi/pesubsec2householdroster8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pesubsec4childcarers1.sav");
sink("../data/ddi/pesubsec4childcarers1.xml");
writeDDI(data,"../data/ddi/pesubsec4childcarers1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pesubsec7chldlivelihoods8.sav");
sink("../data/ddi/pesubsec7chldlivelihoods8.xml");
writeDDI(data,"../data/ddi/pesubsec7chldlivelihoods8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pesubsec7hhlivelihoods1.sav");
sink("../data/ddi/pesubsec7hhlivelihoods1.xml");
writeDDI(data,"../data/ddi/pesubsec7hhlivelihoods1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pesubsec7hhlivelihoods8.sav");
sink("../data/ddi/pesubsec7hhlivelihoods8.xml");
writeDDI(data,"../data/ddi/pesubsec7hhlivelihoods8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pesubsec7indivincome1.sav");
sink("../data/ddi/pesubsec7indivincome1.xml");
writeDDI(data,"../data/ddi/pesubsec7indivincome1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pesubsec7indivincome8.sav");
sink("../data/ddi/pesubsec7indivincome8.xml");
writeDDI(data,"../data/ddi/pesubsec7indivincome8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pesubsec7outgoings1.sav");
sink("../data/ddi/pesubsec7outgoings1.xml");
writeDDI(data,"../data/ddi/pesubsec7outgoings1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pesubsec7outgoings8.sav");
sink("../data/ddi/pesubsec7outgoings8.xml");
writeDDI(data,"../data/ddi/pesubsec7outgoings8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pesubsec7plans1.sav");
sink("../data/ddi/pesubsec7plans1.xml");
writeDDI(data,"../data/ddi/pesubsec7plans1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pesubsec7plans8.sav");
sink("../data/ddi/pesubsec7plans8.xml");
writeDDI(data,"../data/ddi/pesubsec7plans8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pesubsec9plots1.sav");
sink("../data/ddi/pesubsec9plots1.xml");
writeDDI(data,"../data/ddi/pesubsec9plots1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/pesubsec9plots8.sav");
sink("../data/ddi/pesubsec9plots8.xml");
writeDDI(data,"../data/ddi/pesubsec9plots8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/vnchildlevel12yrold.sav");
sink("../data/ddi/vnchildlevel12yrold.xml");
writeDDI(data,"../data/ddi/vnchildlevel12yrold.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/vnchildlevel1yrold.sav");
sink("../data/ddi/vnchildlevel1yrold.xml");
writeDDI(data,"../data/ddi/vnchildlevel1yrold.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/vnchildlevel5yrold.sav");
sink("../data/ddi/vnchildlevel5yrold.xml");
writeDDI(data,"../data/ddi/vnchildlevel5yrold.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/vnchildlevel8yrold.sav");
sink("../data/ddi/vnchildlevel8yrold.xml");
writeDDI(data,"../data/ddi/vnchildlevel8yrold.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/vnchildquest12yrold.sav");
sink("../data/ddi/vnchildquest12yrold.xml");
writeDDI(data,"../data/ddi/vnchildquest12yrold.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/vnsubactivities12.sav");
sink("../data/ddi/vnsubactivities12.xml");
writeDDI(data,"../data/ddi/vnsubactivities12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/vnsubactivities5.sav");
sink("../data/ddi/vnsubactivities5.xml");
writeDDI(data,"../data/ddi/vnsubactivities5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/vnsubchildwork12.sav");
sink("../data/ddi/vnsubchildwork12.xml");
writeDDI(data,"../data/ddi/vnsubchildwork12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/vnsubchildwork5.sav");
sink("../data/ddi/vnsubchildwork5.xml");
writeDDI(data,"../data/ddi/vnsubchildwork5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/vnsubcreche5.sav");
sink("../data/ddi/vnsubcreche5.xml");
writeDDI(data,"../data/ddi/vnsubcreche5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/vnsubcrops12.sav");
sink("../data/ddi/vnsubcrops12.xml");
writeDDI(data,"../data/ddi/vnsubcrops12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/vnsubcrops5.sav");
sink("../data/ddi/vnsubcrops5.xml");
writeDDI(data,"../data/ddi/vnsubcrops5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/vnsubgroups12.sav");
sink("../data/ddi/vnsubgroups12.xml");
writeDDI(data,"../data/ddi/vnsubgroups12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/vnsubgroups5.sav");
sink("../data/ddi/vnsubgroups5.xml");
writeDDI(data,"../data/ddi/vnsubgroups5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/vnsubhouseholdmember12.sav");
sink("../data/ddi/vnsubhouseholdmember12.xml");
writeDDI(data,"../data/ddi/vnsubhouseholdmember12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/vnsubhouseholdmember5.sav");
sink("../data/ddi/vnsubhouseholdmember5.xml");
writeDDI(data,"../data/ddi/vnsubhouseholdmember5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/vnsubillnesses12.sav");
sink("../data/ddi/vnsubillnesses12.xml");
writeDDI(data,"../data/ddi/vnsubillnesses12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/vnsubillnesses5.sav");
sink("../data/ddi/vnsubillnesses5.xml");
writeDDI(data,"../data/ddi/vnsubillnesses5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/vnsubinjuries12.sav");
sink("../data/ddi/vnsubinjuries12.xml");
writeDDI(data,"../data/ddi/vnsubinjuries12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/vnsubinjuries5.sav");
sink("../data/ddi/vnsubinjuries5.xml");
writeDDI(data,"../data/ddi/vnsubinjuries5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/vnsubloans12.sav");
sink("../data/ddi/vnsubloans12.xml");
writeDDI(data,"../data/ddi/vnsubloans12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/vnsubloans5.sav");
sink("../data/ddi/vnsubloans5.xml");
writeDDI(data,"../data/ddi/vnsubloans5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/vnsublongtermhealth12.sav");
sink("../data/ddi/vnsublongtermhealth12.xml");
writeDDI(data,"../data/ddi/vnsublongtermhealth12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/vnsublongtermhealth5.sav");
sink("../data/ddi/vnsublongtermhealth5.xml");
writeDDI(data,"../data/ddi/vnsublongtermhealth5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/vnsuboutgoings12.sav");
sink("../data/ddi/vnsuboutgoings12.xml");
writeDDI(data,"../data/ddi/vnsuboutgoings12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/vnsuboutgoings5.sav");
sink("../data/ddi/vnsuboutgoings5.xml");
writeDDI(data,"../data/ddi/vnsuboutgoings5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/vnsubplotsofland12.sav");
sink("../data/ddi/vnsubplotsofland12.xml");
writeDDI(data,"../data/ddi/vnsubplotsofland12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/vnsubplotsofland5.sav");
sink("../data/ddi/vnsubplotsofland5.xml");
writeDDI(data,"../data/ddi/vnsubplotsofland5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/vnsubpositionsofauthority12.sav");
sink("../data/ddi/vnsubpositionsofauthority12.xml");
writeDDI(data,"../data/ddi/vnsubpositionsofauthority12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/vnsubpositionsofauthority5.sav");
sink("../data/ddi/vnsubpositionsofauthority5.xml");
writeDDI(data,"../data/ddi/vnsubpositionsofauthority5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/vnsubpreschool5.sav");
sink("../data/ddi/vnsubpreschool5.xml");
writeDDI(data,"../data/ddi/vnsubpreschool5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/vnsubprimaryoccupationproductiveassets12.sav");
sink("../data/ddi/vnsubprimaryoccupationproductiveassets12.xml");
writeDDI(data,"../data/ddi/vnsubprimaryoccupationproductiveassets12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/vnsubprimaryoccupationproductiveassets5.sav");
sink("../data/ddi/vnsubprimaryoccupationproductiveassets5.xml");
writeDDI(data,"../data/ddi/vnsubprimaryoccupationproductiveassets5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/vnsubprojects12.sav");
sink("../data/ddi/vnsubprojects12.xml");
writeDDI(data,"../data/ddi/vnsubprojects12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/vnsubprojects5.sav");
sink("../data/ddi/vnsubprojects5.xml");
writeDDI(data,"../data/ddi/vnsubprojects5.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/vnsubsec2householdroster1.sav");
sink("../data/ddi/vnsubsec2householdroster1.xml");
writeDDI(data,"../data/ddi/vnsubsec2householdroster1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/vnsubsec2householdroster8.sav");
sink("../data/ddi/vnsubsec2householdroster8.xml");
writeDDI(data,"../data/ddi/vnsubsec2householdroster8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/vnsubsec4childcarers1.sav");
sink("../data/ddi/vnsubsec4childcarers1.xml");
writeDDI(data,"../data/ddi/vnsubsec4childcarers1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/vnsubsec7chldlivelihoods8.sav");
sink("../data/ddi/vnsubsec7chldlivelihoods8.xml");
writeDDI(data,"../data/ddi/vnsubsec7chldlivelihoods8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/vnsubsec7hhlivelihoods1.sav");
sink("../data/ddi/vnsubsec7hhlivelihoods1.xml");
writeDDI(data,"../data/ddi/vnsubsec7hhlivelihoods1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/vnsubsec7hhlivelihoods8.sav");
sink("../data/ddi/vnsubsec7hhlivelihoods8.xml");
writeDDI(data,"../data/ddi/vnsubsec7hhlivelihoods8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/vnsubsec7indivincome1.sav");
sink("../data/ddi/vnsubsec7indivincome1.xml");
writeDDI(data,"../data/ddi/vnsubsec7indivincome1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/vnsubsec7indivincome8.sav");
sink("../data/ddi/vnsubsec7indivincome8.xml");
writeDDI(data,"../data/ddi/vnsubsec7indivincome8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/vnsubsec7outgoings1.sav");
sink("../data/ddi/vnsubsec7outgoings1.xml");
writeDDI(data,"../data/ddi/vnsubsec7outgoings1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/vnsubsec7outgoings8.sav");
sink("../data/ddi/vnsubsec7outgoings8.xml");
writeDDI(data,"../data/ddi/vnsubsec7outgoings8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/vnsubsec7plans1.sav");
sink("../data/ddi/vnsubsec7plans1.xml");
writeDDI(data,"../data/ddi/vnsubsec7plans1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/vnsubsec7plans8.sav");
sink("../data/ddi/vnsubsec7plans8.xml");
writeDDI(data,"../data/ddi/vnsubsec7plans8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/vnsubsec9plots1.sav");
sink("../data/ddi/vnsubsec9plots1.xml");
writeDDI(data,"../data/ddi/vnsubsec9plots1.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/vnsubsec9plots8.sav");
sink("../data/ddi/vnsubsec9plots8.xml");
writeDDI(data,"../data/ddi/vnsubsec9plots8.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/vnsubsecondaryoccupationproductiveassets12.sav");
sink("../data/ddi/vnsubsecondaryoccupationproductiveassets12.xml");
writeDDI(data,"../data/ddi/vnsubsecondaryoccupationproductiveassets12.xml");
sink();# install.packages("spssDDI");
data<-readSpssSav("../data/spss/vnsubsecondaryoccupationproductiveassets5.sav");
sink("../data/ddi/vnsubsecondaryoccupationproductiveassets5.xml");
writeDDI(data,"../data/ddi/vnsubsecondaryoccupationproductiveassets5.xml");
sink();