<div id="yl-navigation-content" class="width99 init-me-please">
<ul class="index">
  <li class="menu_item"><a href="/">Linked Data Home</a></li>
  <li class="menu_item"><a href="/pages/about">About</a></li>
  <li class="countryPage"><a href="/pages/Ethiopia">Ethiopia</a></li>
  <li class="countryPage"><a href="/pages/India">India</a></li>
  <li class="countryPage"><a href="/pages/Peru">Peru</a></li>
  <li class="countryPage"><a href="/pages/Vietnam">Vietnam</a></li>
  <li class="menu_item"><a href="http://www.younglives.org.uk">Young Lives Homepage </a></li>
</ul>
</div>

