<?php

/**
 * Young Lives Countries box template
 *
 */

#var_dump($this->data);
?>

<div id="yl-navigation-content" class="width99 init-me-please">
<p>Hello Rupert</p>
<p><a href="<?php echo($this->urlBase);?>view/r/ylpages%3AEthiopia?m=http%3A%2F%2Fdata.younglives.org.uk">Go to Ethiopia!</a> If you have imported the test_markdown.ttl
</p>
<?php 
/*php can go here
 
var_dump($this->urlBase);*/
?>    
</div>
