<script type="text/javascript">
    var actionURL = '<?php echo $this->actionUrl; ?>';
    var salt = '<?php echo $this->salt; ?>';
    <?php if( isset($this->modelUri) ){ echo "var graphURI = '".$this->modelUri."';"; }  ?>
    csvConfigs = [];
    <?php
    if( isset($this->configs) ){
        for($i = 0; $i < count($this->configs); $i++ ){
            echo "csvConfigs[".$i."] = '".wordwrap($this->configs[$i], 1024, "'\n+ '")."';\n";
        };
    }?>
</script>
<?php if( isset($this->scovo) ): ?>
<!--<div><?php echo $this->_('Base URI:') ?><input type="text" id="uribase" value="initme" style="width:80%;"></div>-->
<div><?php echo $this->_('Data Range:') ?><span id="csvimportDatarange"></span></div>
<!--<div><?php echo $this->_('Attributes:') ?>-->

<!-- added by neontribe for young lives project, these represent the three core dimensions that must have values -->
<div style="float:right;" class="help_button"><a href="csvimport/help" target="_blank">Give Me Help!</a></div>
<div style="display:none" id="measure_container">
	<fieldset>
		<legend>Choose an existing measure or add a new one</legend>
		<input id="measure_choice-a" type="radio" name="measure_choice_neon" value="existing"/>
			<label for="chort_choice-a">use an existing measure</label>
		<input id="measure_choice-b" type="radio" name="measure_choice_neon" value="new"/>
			<label for="chort_choice-b">make a new measure</label>
	</fieldset>
	<div style="display:none" id="existing_measure">
		<label for="existing_measure_select">Select measure:</label>
		<select id="existing_measure_select" name="existing_measure_select">
			<option value="use_existing_measure"> </option>
			<!-- options to be added by script after being retrieved from ontowiki -->
		</select>
	</div>
	<div style="display:none" id="new_measure">
		<label for="new_measure_type">Measure Type:  </label>
			http://www.w3.org/2001/XMLSchema#<input type="text" name="new_measure_type" id="new_measure_type" value="decimal"/><br />
		<label for="new_measure_label">Measure Label:  </label>
			<input type="text" name="new_measure_label" id="new_measure_label" value="" size="75"/>
		Please make this unique.<br />
		<label for="new_measure_name">Name for Measure:  </label>
			<input type="text" name="new_measure_name" id="new_measure_name" value="" />*<br />
		* if the name of an existing measure is used, then that measure is used and this data is ignored.<br />
	</div>
</div>
<div id="select_country_container">
	<label for="select_country">Select country:</label>
	<select id="select_country" name="select_country" >
		<option value="Ethiopia">Ethiopia</option>
		<option value="India" selected="selected">India</option>
		<option value="Peru">Peru</option>
		<option value="Vietnam">Vietnam</option>
	</select>
</div>
<!--<div id="select_round_container">
	<label for="select_round">Select round:</label>
	<select id="select_round" name="select_round" >
		<option value="roundOne">round one</option>
		<option value="roundTwo">round two</option>
		<option value="roundThree" selected="selected">round three</option>
		<option value="roundFour">round four</option>
		<option value="roundFive">round five</option>
	</select>
</div>-->
<div id="select_cohort_container">
	<fieldset>
		<legend>Choose fixed cohort or dynamic cohort values from spread sheet</legend>
		<input id="chort_choice-a" type="radio" name="cohort_choice" value="fixed"/>
			<label for="chort_choice-a">use fixed value</label>
		<input id="chort_choice-b" type="radio" name="cohort_choice" value="sheet"/>
			<label for="chort_choice-b">use spreadsheet values</label>
	</fieldset>
	<div style="display:none" id="fixed_cohort">
		<fieldset>
			<legend>Choose a cohort</legend>
			<input id="chort_choice-young" type="radio" name="which_cohort" value="YoungCohort"/>
				<label for="chort_choice-young">Young Cohort</label>
			<input id="chort_choice-old" type="radio" name="which_cohort" value="OldCohort"/>
				<label for="chort_choice-old">Old Cohort</label>
			<input id="chort_choice-all" type="radio" name="which_cohort" value="AllCohorts"/>
				<label for="chort_choice-all">All Cohorts</label>
		</fieldset>
	</div>
	<div style="display:none" id="sheet_cohort">
		<span class="uri">http://data.younglives.org.uk/component#</span><input type="text" readonly="true" value="cohort" name="dimension_cohort" /><a class="button" id="btn_dim_cohort" ><img src="<?php $this->_componentUrlBase ?>extensions/themes/silverblue/images/icon-add.png"/><span>&nbsp;Select Sheet Values</span></a></span>
	</div>
</div>
<div id="sheet_dimensions">
	<!-- place for added dimensions to go -->
</div>
<script>
$(document).ready(function () {
/*code in csvimport .js
this is a place holder 
TODO remove later if not needed
*/
});

</script>
<!--
<table id="csvimport-attributes">
    <tr>
        <th><?php echo $this->_('Attribute Name') ?></th>
    </tr>
</table>
-->
</div>
<!--<div><?php echo $this->_('Dimensions:') ?>

<table id="csvimport-dimensions">
    <tr>
        <th><?php echo $this->_('Dimension Name') ?></th>
    </tr>
</table>

</div>-->
<?php endif; ?>
<div style="position: relative; overflow: auto; width: 100%; height: 100%;" id="table-holder">
<?php echo $this->table ?>
</div>
