this is the application/views/templates/index/news.phtml. We can put front page html here. Note applications/controllers/IndexController.php has been tweeked to turn off the fetching of news stories and a class var for the name of this box added to stop it saying 'News'
<!--<?php foreach ($this->feed as $feedItem): ?>
    <div class="messagebox feed">
        <h2><a href="<?php echo $feedItem->link() ?>"><?php echo $feedItem->title() ?></a></h2>
        <p><?php echo $feedItem->description() ?></p>
    </div>
<?php endforeach; ?>-->