<div style="text-align:center; width:740px; margin-left:auto; margin-right:auto;">
<img id="Image-Maps_7201202241137181" src="http://data.younglives.org.uk/uploads/Map.png" usemap="#Image-Maps_7201202241137181" border="0" width="740" height="382" alt="" />
<map id="_Image-Maps_7201202241137181" name="Image-Maps_7201202241137181">
<area shape="rect" coords="158,194,238,269" href="http://data.younglives.org.uk/pages/Peru" alt="Peru country page" title="Peru country page"    />
<area shape="rect" coords="381,181,461,256" href="http://data.younglives.org.uk/pages/Ethiopia" alt="Ethiopia country page" title="Ethiopia country page"    />
<area shape="rect" coords="469,139,536,212" href="http://data.younglives.org.uk/pages/India" alt="India country page" title="India country page"    />
<area shape="rect" coords="535,174,601,248" href="http://data.younglives.org.uk/pages/Vietnam" alt="Vietnam country page" title="Vietnam country page"    />
</map>
</div>
<h2>Young Lives Linked Data</h2>
<p>
This pilot site provides access to linked data from the Young Lives study. 
</p>
<p>
Select a country above to view selected statistics and country information, or search or browse the available data from the options on the left. 
</p>
<p>
You can find out <a href="/pages/about">more about this site and it's use of linked data here</a>.
</p>

<p>
</p>
<h3>Young Lives Microdata</h3>
<p>
Detailed microdata datasets from young lives are also available for researchers from the UK Public Data Archive and on CD from Principle Investigators in study countries. See the '<a href="http://www.younglives.org.uk/what-we-do/access-our-data/access-our-data">Access our Data</a>' pages for details. 
</p>
