<?php
$params = array();
$params[] = 'dsd=' . urlencode($this->resource);
$params[] = 'sparql_endpoint=' . urlencode($this->base . 'service/sparql');
$params[] = 'grapher_host=' . urlencode($_SERVER['HTTP_HOST']);
$params[] = 'ontowiki_path=' . urlencode($_SERVER['REDIRECT_URL']);
$params[] = 'grapher_path=' . urlencode($this->componentBase . 'graphing/grapher/grapher.html');
foreach ($_GET as $k => $v) {
   $val = $k . '=' .  urlencode($v);
   if (!in_array($val, $params)) {
        $params[] = $val;
   }
}
$q = implode('&', $params);

?>
<iframe
        src="<?php echo $this->componentBase; ?>graphing/grapher/grapher.html?<?php echo $q; ?>"
        style="width:633px;height:500px;"
        scrolling="no"
        frameborder="0"

        >young lives graphing iframe</iframe>
