<?php
$params = array();
$params[] = 'activeDSD=' . urlencode($this->resource);
$params[] = 'sparql_endpoint=' . urlencode($this->base . 'service/sparql');
$params[] = 'http_host=' . urlencode($_SERVER['HTTP_HOST']);
$params[] = 'host_path=' . urlencode($_SERVER['REDIRECT_URL']);
foreach ($_GET as $k => $v) {
   $val = $k . '=' .  urlencode($v);
   if (!in_array($val, $params)) {
        $params[] = $val;
   }  
}
$q = implode('&', $params);

?>
<iframe src="<?php echo $this->componentBase; ?>graphing/graph.html?<?php echo $q; ?>" style="width:100%;height:500px;">young lives graphing iframe</iframe>
